# Collabrative Filtering data set taken from Collective Intelligence book.


dataset_age= {
			'Eric': {'Lady in the Water': 25.0, 
							'Snakes on a Plane': 35.0,
							'Just My Luck': 30.0, 
							'Superman Returns': 35.0, 
							'You, Me and Dupree': 25.0,
							'The Night Listener': 30.0},
			'Ramlin': {'Lady in the Water': 30.0, 
							'Snakes on a Plane': 35.0,
							'Just My Luck': 15.0,
							 'Superman Returns': 50.0, 
							 'The Night Listener': 30.0,
							'You, Me and Dupree': 35.0},

			'Mark': {'Lady in the Water': 25.0, 
								'Snakes on a Plane': 30.0,
								'Superman Returns': 35.0,
								 'The Night Listener': 40.0},
			'Zack': {'Snakes on a Plane': 35.0, 
							'Just My Luck': 30.0,
							'The Night Listener': 45.0, 
							'Superman Returns': 40.0,
							'You, Me and Dupree': 25.0},
			'Effron': {'Lady in the Water': 30.0, 
							'Snakes on a Plane': 40.0,
							'Just My Luck': 20.0, 
							'Superman Returns': 30.0, 
							'The Night Listener': 30.0,
							'You, Me and Dupree': 20.0},
			'Codey': {'Lady in the Water': 30.0, 
							'Snakes on a Plane': 40.0,
							'The Night Listener': 30.0, 
							'Superman Returns': 50.0, 
							'You, Me and Dupree': 35.0},
			'Arck': {'Snakes on a Plane':45.0,
					'You, Me and Dupree':10.0,
					'Superman Returns':40.0}}
